### ISSUE TITLE
Fail open the UI. java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes...

### ISSUE THREAD

**Issue by marcelomrwin** [microprofile-extensions/openapi-ext#29]
When trying to work with the UI using 1.1.4 Version the following occurs:

 85 more
Caused by: java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
	at org.microprofileext.openapi.swaggerui.Templates.getLogo(Templates.java:121)
	at org.microprofileext.openapi.swaggerui.Templates.afterCreate(Templates.java:46)
	... 90 more

**Comment by phillip-kruger** [comment]
Hi @marcelomrwin , what version of java are you using ?

**Comment by phillip-kruger** [comment]
Closing - no feedback. please reopen if needed.
